In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
df = pd.read_csv("matches.csv")
df

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [9]:
df.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [10]:
df.tail()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [11]:
df.describe()

,id,season,dl_applied,win_by_runs,win_by_wickets,umpire3
count,636.000000,636.000000,636.000000,636.000000,636.000000,0.0
mean,318.500000,2012.490566,0.025157,13.682390,3.372642,NaN
std,183.741666,2.773026,0.156726,23.908877,3.420338,NaN
min,1.000000,2008.000000,0.000000,0.000000,0.000000,NaN
25%,159.750000,2010.000000,0.000000,0.000000,0.000000,NaN
50%,318.500000,2012.000000,0.000000,0.000000,4.000000,NaN
75%,477.250000,2015.000000,0.000000,20.000000,7.000000,NaN
max,636.000000,2017.000000,1.000000,146.000000,10.000000,NaN

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               636 non-null    int64
 1   season           636 non-null    int64
 2   city             629 non-null    object
 3   date             636 non-null    object
 4   team1            636 non-null    object
 5   team2            636 non-null    object
 6   toss_winner      636 non-null    object
 7   toss_decision    636 non-null    object
 8   result           636 non-null    object
 9   dl_applied       636 non-null    int64
 10  winner           633 non-null    object
 11  win_by_runs      636 non-null    int64
 12  win_by_wickets   636 non-null    int64
 13  player_of_match  633 non-null    object
 14  venue            636 non-null    object
 15  umpire1          635 non-null    object
 16  umpire2          635 non-null    object
 17  umpire3          0 non-null      float64
dtypes: float64(1), int64(5), object(12)
memory usage: 89.6+ KB

In [13]:
df

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [16]:
df.isnull().any()

id                 False
season             False
city                True
date               False
team1              False
team2              False
toss_winner        False
toss_decision      False
result             False
dl_applied         False
winner              True
win_by_runs        False
win_by_wickets     False
player_of_match     True
venue              False
umpire1             True
umpire2             True
umpire3             True
dtype: bool

In [19]:
df[['city','venue']]

          city                                             venue
0    Hyderabad         Rajiv Gandhi International Stadium, Uppal
1         Pune           Maharashtra Cricket Association Stadium
2       Rajkot            Saurashtra Cricket Association Stadium
3       Indore                            Holkar Cricket Stadium
4    Bangalore                             M Chinnaswamy Stadium
..         ...                                               ...
631     Raipur  Shaheed Veer Narayan Singh International Stadium
632  Bangalore                             M Chinnaswamy Stadium
633      Delhi                                  Feroz Shah Kotla
634      Delhi                                  Feroz Shah Kotla
635  Bangalore                             M Chinnaswamy Stadium

[636 rows x 2 columns]

In [24]:
matches = df[['win_by_runs','win_by_wickets']]

In [25]:
X = matches['win_by_runs']
y = matches['win_by_wickets']

In [29]:
X.ravel()

array([ 35,   0,   0,   0,  15,   0,   0,   0,  97,   0,   0,   0,   0,
        17,  51,   0,  27,   0,   5,  21,  15,   0,   0,  14,   0,  26,
        82,   3,   0,   0,   0,  26,  61,   0,   0,  48,   0,   0,   0,
         0,   0,  19,  12, 146,   0,   0,   0,  14,   0,   7,   7,   0,
         9,   0,  10,  20,   0,   0,   1, 140,  33,   0,   0,   0,   0,
         0,   6,   0,  66,   0,   0,   0,   0,  13,   0,  10,   0,  45,
         0,   0,   9,  29,   0,   0,   0,   0,   0,   5,   0,   0,  18,
        23,   0,   0,  23,   0,  41,  12,   0,   6,  65,  25,   3,   0,
         0,   1,  14,   0,   0,  10,   3,   0,   0,   0, 105,   0,   0,
        19,  75,   0,   0,  92,  11,  24,   9,   0,   0,  12,   0,  27,
         0,  92,   0,   0,   3,   0,  38,   9,   8,   0,  18,   0,   0,
        78,  78,   0,  19,   0,  12,   0,   0,   0,  16,   0,  53,   0,
         0,  12,   0,   2,   0,   0,   0,   1,  14,   0,   0,   0,  24,
         0,  12,   0,   0,   6,  11,   4,   0,   0,  31,   0,   0,  55,
        98,   0,   0,   6,  34,   0,  10,   0,   0,  36,  31,   0,   0,
        39,  17,  17,  41,  40,   0,   0,  67,  24,   0,  23,  63,   0,
        37,   2,  24,   0,  14,   0,   0,   0,   0,   0,  37,  13,  39,
         0,   0,   0,   0,  57,   0,   0,  11,   0,  35,  38,   0,  22,
         2,   0,   0,   0,   0,   9,   0,   0,   0,   0,  33,   0,   0,
        21,   0,   0,   0,   0,  16,   0,   6,  48,   8,   0,  29,  37,
         0,  25,   0,   0,  55,  17,   0,  26,  38,   0,   0,  19,  23,
         0,  20,   0,  21,  17,   0,  85,  10,  32,   0,   0,  63,   0,
        76,   0,  18,   0,   0,  10,  29,   0,   0, 111,  11,   0,   0,
        82,   0,   0,   0,   0,   0,  43,  58,   0,   0,  28,  31,  20,
        74,  22,  22,   0,  42,   0,  27,   0,   0,   0,   0,   0,   2,
        59,   0,   0,   0,   0,   0,  13,   0,   0,  20,   0,   0,  46,
         0,   0,  18,  37,   7,  47,   1,   0,   0,  13,   0,   0,   1,
        10,   7,  43,   0,   0,   0,   0,  25,   0,   0,  35,  27,   0,
        45,   0,   0,   0,   0,  32,   0,  21,   0,   0,  34,   9,   0,
        18,  38,  86,   0,   0,   2,  22,   5,   9,   0,   0,  19,  44,
         0,   0,   0,   0,  41,   0,  48,   0,  24,   4,   0,  11,  87,
        86,   0,   0,   0,   0,   0,   0, 130,   7,   0,   0,   0,   0,
        58,  14,  15,   0,   4,  37,   0,   0,  15,  17,   0,   0,   0,
        60,   0,   0,   0,  65,  77,   0,  46,   4,   0,  30,   0,   0,
         0,   0,   7,  33,  14,   0,  23,  50,  38,  24,   0,  48,   0,
         0,  23,  41,   0,   0,   0,   0,   0,   0,  93,  72,   7,   2,
         4,   0,   0,  23,   0,   0,   0,   0,  15,  34,   0,   0,   0,
        10,   0,  19,   0,  44,  32,  32,   0,   0,   0,   0,   0,   0,
        16,   0,   0,  62,   0,   0,  25,   0,   0,   0,   0,  30,   0,
        15,  16,   0,   0,   0,   0,  28,   0,  24,   0,   0,   1,  26,
        45,   0,   0,  18,   0,   0,   0,   0,   0,   0,   4,   0,   0,
        18,   0,   0,  16,  27,  37,   0,  20,  97,   0,  20,  13,   0,
         2,   0,   8,   0,  22,  23,  14,  24,  35,   0, 138,   7,   0,
         0,   6,  39,  12,   5,   0,  22,   5,   0,   0,   9,   0,   0,
        25,  71,   0,  41,   0,   0,   0,  45,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,  13,  10,   0,   0,   0,  25,  34,
         1,   0,   0,  27,  15,  23,   0,   0,   0,   7,   0,   0,   0,
         9,  85,   0,   1,   4,   0,   0,   0, 144,   0,   0,  80,   0,
        19,  82,   0,   0,   0,   0,  22,   0,   0,  22,   0,   8],
      dtype=int64)